<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<script src="../../resources/js-test-pre.js"></script>
</head>
<body>
<script>

// Adapted from http://dxr.mozilla.org/mozilla-central/source/dom/promise/tests/test_promise.html which stated:
//    Any copyright is dedicated to the Public Domain.
//    http://creativecommons.org/publicdomain/zero/1.0/

description("Promises - Adapted from http://dxr.mozilla.org/mozilla-central/source/dom/promise/tests/test_promise.html.");

window.jsTestIsAsync = true;

function test(_a, _b)
{
    if (isResultCorrect(_a, _b))
        testPassed(stringify(_a) + " is " + stringify(_b));
    else
        testFailed(stringify(_a) + " should be " + stringify(_b));
}

function promiseResolve() {
  debug("Test Promise resolve.")
  
  var promise = new Promise(function(resolver) {
    resolver.resolve(42);
  }).then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 42);
    runTest();
  }, function() {
    testFailed("Then.reject has been called");
    runTest();
  });
}

function promiseReject() {
  debug("Test Promise reject.");
  
  var promise = new Promise(function(resolver) {
    resolver.reject(42);
  }).then(function(what) {
    testFailed("Then.resolve has been called");
    runTest();
  }, function(what) {
    testPassed("Then.reject has been called");
    test(what, 42);
    runTest();
  });
}

function promiseException() {
  debug("Test Promise reject.");

  var promise = new Promise(function(resolver) {
    throw 42;
  }).then(function(what) {
    testFailed("Then.resolve has been called");
    runTest();
  }, function(what) {
    testPassed("Then.reject has been called");
    test(what, 42);
    runTest();
  });
}

function promiseGC() {
  debug("Test Promise gc.");
  
  var resolver;
  var promise = new Promise(function(r) {
    resolver = r;
  }).then(function(what) {
    testPassed("Then - promise is still alive");
    runTest();
  });

  promise = null;

  gc();

  resolver.resolve(42);
}

function promiseAsync() {
  debug("Test Promise async.");

  var global = "foo";
  var f = new Promise(function(r) {
    debug("Global should be foo");
    test(global, 'foo');

    r.resolve(42);

    debug("Global should still be foo");
    test(global, 'foo');

    setTimeout(function() {
      debug("Global should be bar");
      test(global, 'bar');
      runTest();
    }, 0);
  }).then(function() {
    global = "bar";
  });

  debug("Global should still be foo (2)");
  test(global, 'foo');
}

function promiseDoubleThen() {
  debug("Test Promise double then.");

  var steps = 0;
  var promise = new Promise(function(resolver) {
    resolver.resolve(42);
  });

  promise.then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 42);
    steps++;
  }, function(what) {
    testFailed("Then.reject has been called");
  });

  promise.then(function(what) {
    testPassed("Then.resolve has been called");
    test(steps, 1);
    test(what, 42);
    runTest();
  }, function(what) {
    testFailed("Then.reject has been called");
  });
}

function promiseThenException() {
  debug("Test Promise - then / exception.");

  var promise = new Promise(function(resolver) {
    resolver.resolve(42);
  });

  promise.then(function(what) {
    testPassed("Then.resolve has been called");
    throw "booh";
  }).catch(function(e) {
    testPassed("Catch handler (e.g. the reject handler) called.");
    runTest();
  });
}

function promiseThenCatchThen() {
  debug("Test Promise - then / catch / then.");

  var promise = new Promise(function(resolver) {
    resolver.resolve(42);
  });

  var promise2 = promise.then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 42);
    return what + 1;
  }, function(what) {
    testFailed("Then.reject has been called");
  });

  promise2.then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 43);
    return what + 1;
  }, function(what) {
    testFailed("Then.reject has been called");
  }).catch(function() {
    testFailed("Catch has been called");
  }).then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 44);
    runTest();
  }, function(what) {
    testFailed("Then.reject has been called");
  });
}

function promiseRejectThenCatchThen() {
  debug("Test Promise - reject / then / catch / then.");

  var promise = new Promise(function(resolver) {
    resolver.reject(42);
  });

  var promise2 = promise.then(function(what) {
    testFailed("Then.resolve has been called");
  }, function(what) {
    testPassed("Then.reject has been called");
    test(what, 42);
    return what + 1;
  });

  promise2.then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 43);
    return what + 1;
  }).catch(function(what) {
    testFailed("Catch has been called");
  }).then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 44);
    runTest();
  });
}

function promiseRejectThenCatchThen2() {
  debug("Test Promise - reject / then / catch / then (2).");

  var promise = new Promise(function(resolver) {
    resolver.reject(42);
  });

  promise.then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 42);
    return what + 1;
  }).catch(function(what) {
    testPassed("Catch has been called");
    test(what, 42);
    return what + 1;
  }).then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 43);
    runTest();
  });
}

function promiseRejectThenCatchExceptionThen() {
  debug("Test Promise - reject / then / catch exception / then.");

  var promise = new Promise(function(resolver) {
    resolver.reject(42);
  });

  promise.then(function(what) {
    testFailed("Then.resolve has been called");
  }, function(what) {
    testPassed("Then.reject has been called");
    test(what, 42);
    throw(what + 1);
  }).catch(function(what) {
    testPassed("Catch has been called");
    test(what, 43);
    return what + 1;
  }).then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 44);
    runTest();
  });
}

function promiseThenCatchOrderingResolve() {
  debug("Test Promise - then / catch ordering (resolve).");

  var global = 0;
  var f = new Promise(function(r) {
    r.resolve(42);
  });

  f.then(function() {
    f.then(function() {
      global++;
    });
    f.catch(function() {
      global++;
    });
    f.then(function() {
      global++;
    });
    setTimeout(function() {
      debug("Many steps... should return 2");
      test(global, 2);
      runTest();
    }, 0);
  });
}

function promiseThenCatchOrderingReject() {
  debug("Test Promise - then / catch ordering (reject).");

  var global = 0;
  var f = new Promise(function(r) {
    r.reject(42);
  })

  f.then(function() {}, function() {
    f.then(function() {
      global++;
    });
    f.catch(function() {
      global++;
    });
    f.then(function() {}, function() {
      global++;
    });
    setTimeout(function() {
      debug("Many steps... should return 2");
      test(global, 2);
      runTest();
    }, 0);
  });
}

function promiseNestedPromise() {
  debug("Test Promise - nested promise");

  new Promise(function(resolver) {
    resolver.resolve(new Promise(function(r) {
      testPassed("Nested promise is executed");
      r.resolve(42);
    }));
  }).then(function(value) {
    testPassed("Then.resolve has been called");
    test(value, 42);
    runTest();
  });
}

function promiseNestedNestedPromise() {
  debug("Test Promise - nested-nested promise.");

  new Promise(function(resolver) {
    resolver.resolve(new Promise(function(r) {
      testPassed("Nested promise is executed");
      r.resolve(42);
    }).then(function(what) { return what + 1; }));
  }).then(function(value) {
    testPassed("Then.resolve has been called");
    test(value, 43);
    runTest();
  });
}

function promiseWrongNestedPromise() {
  debug("Test Promise - wrong nested promise.");

  new Promise(function(resolver) {
    resolver.resolve(new Promise(function(r) {
      testPassed("Nested promise is executed");
      r.resolve(42);
    }));
    resolver.reject(42);
  }).then(function(value) {
    testPassed("Then.resolve has been called");
    test(value, 42);
    runTest();
  }, function(value) {
    testFailed("Then.reject has been called");
  });
}

function promiseLoop() {
  debug("Test Promise - promise loop.");

  new Promise(function(resolver) {
    resolver.resolve(new Promise(function(r) {
      testPassed("Nested promise is executed");
      r.resolve(new Promise(function(r) {
        testPassed("Nested-nested promise is executed");
        r.resolve(42);
      }));
    }));
  }).then(function(value) {
    testPassed("Then.resolve has been called");
    test(value, 42);
    runTest();
  }, function(value) {
    testFailed("Then.reject has been called");
  });
}

function promiseRejectConstructor() {
  debug("Test Promise - Promise.reject().");

  var promise = Promise.reject(42).then(function(what) {
    testFailed("Then.resolve has been called");
  }, function(what) {
    testPassed("Then.reject has been called");
    test(what, 42);
    runTest();
  });
}

function promiseResolveConstructor() {
  debug("Test Promise - Promise.resolve().");

  var promise = Promise.resolve(42).then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 42);
    runTest();
  }, function() {
    testFailed("Then.reject has been called");
  });
}

function promiseResolveConstructorNestedPromise() {
  debug("Test Promise - Promise.resolve() with  nested promise.");

  var promise = Promise.resolve(new Promise(function(r) {
    testPassed("Nested promise is executed");
    r.resolve(42);
  }, function() {
    testFailed("Second argument to Promise constructor called.");
  })).then(function(what) {
    testPassed("Then.resolve has been called");
    test(what, 42);
    runTest();
  }, function() {
    testFailed("Then.reject has been called");
  });
}

var tests = [
    promiseResolve,
    promiseReject,
    promiseException,
    promiseGC,
    promiseAsync,
    promiseDoubleThen,
    promiseThenException,
    promiseThenCatchThen,
    promiseRejectThenCatchThen,
    promiseRejectThenCatchThen2,
    promiseRejectThenCatchExceptionThen,
    promiseThenCatchOrderingResolve,
    promiseThenCatchOrderingReject,
    promiseNestedPromise,
    promiseNestedNestedPromise,
    promiseWrongNestedPromise,
    promiseLoop,
    promiseRejectConstructor, 
    promiseResolveConstructor,
    promiseResolveConstructorNestedPromise,
];

function runTest() {
  if (!tests.length) {
    finishJSTest();
    return;
  }

  debug("");
  var test = tests.shift();
  test();
}

runTest();

</script>
<script src="../../resources/js-test-post.js"></script>
</body>
</html>
